import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useStore } from '../lib/store';
import { MapPin, Phone, CheckCircle2, Navigation, ShoppingBag } from 'lucide-react';
const DeliveryDashboard = () => {
    const { orders } = useStore();
    const deliveryOrders = orders.filter(o => o.status === 'dispatched' || o.status === 'ready');
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-gradient-to-r from-blue-600 to-indigo-700 rounded-3xl p-8 text-white shadow-xl shadow-blue-200", children: [_jsx("h1", { className: "text-3xl font-bold mb-2", children: "Rider Dashboard" }), _jsxs("p", { className: "text-blue-100 font-medium", children: ["You have ", deliveryOrders.length, " active deliveries today"] })] }), _jsx("div", { className: "space-y-4", children: deliveryOrders.map(order => (_jsxs("div", { className: "bg-white rounded-2xl border border-slate-200 p-6 shadow-sm hover:shadow-md transition-all", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-12 h-12 bg-blue-50 rounded-xl flex items-center justify-center text-blue-600", children: _jsx(ShoppingBag, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-slate-900", children: order.customer_name }), _jsxs("p", { className: "text-xs text-slate-500", children: ["#", order.order_number, " \u2022 ", order.delivery_type] })] })] }), _jsx("button", { className: "p-3 bg-blue-600 text-white rounded-xl shadow-lg shadow-blue-100", children: _jsx(Navigation, { className: "w-5 h-5" }) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 mb-6", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm text-slate-600", children: [_jsx(MapPin, { className: "w-4 h-4 text-slate-400" }), _jsx("span", { className: "truncate", children: order.outlet_name })] }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-slate-600", children: [_jsx(Phone, { className: "w-4 h-4 text-slate-400" }), _jsx("span", { children: order.customer_phone })] })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { className: "flex-1 bg-slate-900 text-white py-3 rounded-xl font-bold hover:bg-slate-800 transition-all", children: "Update Status" }), _jsxs("button", { className: "flex-1 bg-green-600 text-white py-3 rounded-xl font-bold hover:bg-green-700 transition-all flex items-center justify-center gap-2", children: ["Mark Delivered ", _jsx(CheckCircle2, { className: "w-5 h-5" })] })] })] }, order.id))) })] }));
};
export default DeliveryDashboard;
