import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useStore } from '../lib/store';
import { Clock, ShoppingBag, Plus } from 'lucide-react';
const OutletDashboard = () => {
    const { orders, currentOutlet } = useStore();
    const outletOrders = orders.filter(o => currentOutlet === 'all' || o.outlet_name.toLowerCase().includes(currentOutlet.toLowerCase()));
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-slate-900", children: "Outlet Panel" }), _jsx("p", { className: "text-slate-500", children: "Manage daily orders and production" })] }), _jsxs("button", { className: "flex items-center gap-2 px-6 py-2.5 bg-amber-600 text-white rounded-xl font-bold hover:bg-amber-700 transition-all shadow-lg shadow-amber-200", children: [_jsx(Plus, { className: "w-5 h-5" }), " New Counter Order"] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: outletOrders.map(order => (_jsxs("div", { className: "bg-white rounded-2xl border border-slate-200 p-6 shadow-sm hover:shadow-md transition-all", children: [_jsxs("div", { className: "flex justify-between items-start mb-4", children: [_jsxs("div", { children: [_jsxs("span", { className: "text-[10px] font-black text-slate-400 uppercase tracking-widest", children: ["#", order.order_number] }), _jsx("h3", { className: "font-bold text-slate-900", children: order.customer_name })] }), _jsx("div", { className: `px-2 py-1 rounded-lg text-[10px] font-bold uppercase ${order.status === 'ready' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`, children: order.status })] }), _jsxs("div", { className: "space-y-3 mb-6", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm text-slate-600", children: [_jsx(ShoppingBag, { className: "w-4 h-4 text-slate-400" }), _jsx("span", { className: "truncate", children: order.items })] }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-slate-600", children: [_jsx(Clock, { className: "w-4 h-4 text-slate-400" }), _jsx("span", { children: order.delivery_time })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { className: "flex-1 bg-green-600 text-white py-2 rounded-lg text-xs font-bold hover:bg-green-700 transition-all", children: "Mark Ready" }), _jsx("button", { className: "px-3 py-2 bg-slate-50 text-slate-600 rounded-lg text-xs font-bold hover:bg-slate-100 border border-slate-200", children: "Details" })] })] }, order.id))) })] }));
};
export default OutletDashboard;
